name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download tests
        env:
          ANSWERS: ${{ secrets.PRAC_1_ANSWERS }}
        run: |
          curl -L "$ANSWERS" -o prac_1_test.py

      - name: test
        run: ls

      - name: Practical 1 tests
        id: python-test
        uses: classroom-resources/autograding-python-grader@v1

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env: 
          PYTHON-TEST_RESULTS: "${{steps.python-test.outputs.result}}"
        with:
          runners: python-test
