name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: actions/setup-python@v5
      with: 
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r requirements.txt

    - name: Download tests
      env:
        ANSWERS: ${{ secrets.PRAC_1_ANSWERS }}
      run: |
        curl -L "$ANSWERS" -o prac_1_test.py

    - name: Practical 1 tests
      id: python-test
      uses: classroom-resources/autograding-python-grader@v1

    - name: Autograding Reporter
      uses: ./
      env: 
        PYTHON-TEST_RESULTS: "${{steps.python-test.outputs.result}}"
      with:
        runners: python-test

  
