name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download tests
        env:
          ANSWERS: ${{ secrets.PRAC_1_ANSWERS }}
        run: |
          curl -L "$ANSWERS" -o prac_1_test.py

      - name: Run Practical 1 tests
        run: pytest -q --tb-short
      
